### ISSUE TITLE
Need category name in check-in report

### ISSUE THREAD

**Issue by brandogamus** [CorWatts/fasterscale#194]
### How do we reproduce the problem?
In my check-in report, I need to see the titles of the category (F. A. S. T. E. or R.) in addition to the subcategory/action that characterizes the category for the check in. This will help me more easily share with my group which letter I'm referring to during my check in.

### Additional info
| Q                            | A
| ---------------------------- | ---
| PHP version                  |
| Operating System and Browser |

**Comment by CorWatts** [comment]
I assume you're talking about the email report? The category titles are above the "Selected Behaviors" section. Do you mean the "Question Responses" section?

Looks like it's a similar story with the website (the /checkin/view page). The Behaviors list has the categories and Questions don't.

<img width="608" alt="Screen Shot 2021-04-05 at 8 09 15 PM" src="https://user-images.githubusercontent.com/220260/113653503-cdd58180-964a-11eb-859f-575be9ca16e5.png">

**Comment by brandogamus** [comment]
Hi Corey,

Yes, exactly – in the “question responses” section, I would like to see the category titles listed (Forgetting priorities, anxiety, etc). A few of the guys in my group are using the Faster Scale app/site now, and I’ve noticed that we’re always trying to remember which category corresponds with our question responses at the top of the report. Hard to remember in the moment and requires scrolling down. I’ve found this to be true on both the email and web reports.

For example (from your attachment), I can see that you wrote “secrets,” but I can’t remember if that’s associated with forgetting priorities or anxiety until I scroll down and look in the selected behaviors section. If the category was also listed at the top with the question responses (ex: forgetting priorities: secrets), it would be easier to share with my group more fluidly. “For me this week, forgetting priorities looked like keeping secrets from my wife.”

Thanks for writing me – and thank you for developing this excellent tool.
Brandon

From: Corey Watts ***@***.***>
Reply-To: CorWatts/fasterscale ***@***.***>
Date: Tuesday, April 6, 2021 at 08:12
To: CorWatts/fasterscale ***@***.***>
Cc: Brandon Pearce ***@***.***>, Author ***@***.***>
Subject: Re: [CorWatts/fasterscale] Need category name in check-in report (#194)


I assume you're talking about the email report? The category titles are above the "Selected Behaviors" section. Do you mean the "Question Responses" section?

Looks like it's a similar story with the website (the /checkin/view page). The Behaviors list has the categories and Questions don't.

[Screen Shot 2021-04-05 at 8 09 15 PM]<https://user-images.githubusercontent.com/220260/113653503-cdd58180-964a-11eb-859f-575be9ca16e5.png>

**Comment by CorWatts** [comment]
Thanks Brandon, that makes sense. That's a very reasonable request!

I'll look into adding this additional text to both the site and the email report. I'll leave this issue open as I do that.

**Comment by CorWatts** [comment]
Hey Brandon, I've added the category name to both the website and the email report and deployed the update. I hope that helps. Please let me know what you think!

**Comment by brandogamus** [comment]
Hey Corey,

The last two times that I’ve tried to use the FASTER scale check in, the results have been mixed up. Can you check that for me?

From the attached screenshot: I chose “roving eyes / lustful thoughts” for Forgetting Priorities (which shows correctly here), but then what I’ve typed below it is my description from Ticked Off’s “overreacting.” The long paragraphs (answers to the questions) are in the wrong places.

Thanks,
Brandon

From: Corey Watts ***@***.***>
Reply-To: CorWatts/fasterscale ***@***.***>
Date: Thursday, April 15, 2021 at 09:12
To: CorWatts/fasterscale ***@***.***>
Cc: Brandon Pearce ***@***.***>, Author ***@***.***>
Subject: Re: [CorWatts/fasterscale] Need category name in check-in report (#194)


Hey Brandon, I've added the category name to both the website and the email report and deployed the update. I hope that helps. Please let me know what you think!

**Comment by CorWatts** [comment]
Hey Brandon, I've tried but have been unable to reproduce this. Also I don't think your screenshots came through. If you could re-send those I'd appreciate it.

To clarify -- you see this issue in the /checkin/view page in your browser, right? Not the emailed report.

**Comment by brandogamus** [comment]
Yep, that’s the check in/view page, I haven’t checked the emailed report. If they are not mixed up, I can just use them instead for the time being. You sure my screenshot didn’t send? Looks like they sent through on my end.

Brandon

Brandon P
________________________________

**Comment by CorWatts** [comment]
I think Github doesn't pass email attachments through this issue system.

I was able to reproduce the issue you mentioned. I created a "Personal Behavior" under Forgetting Priorities and indeed the processing question answers were mixed up with the default behavior answers. I'll dive in and see what's going wrong here.

**Comment by CorWatts** [comment]
Just a quick -- and very belated -- update. This is indeed a bug though we already knew that :)

I've dug into this bug several times but have been unable to identify and fix the primary cause. Unfortunately it's difficult for me to arrange significant blocks of time to devote to programming/debugging. I'll continue to spend time looking into this. I know it's an inconvenient and noticeable issue.

**Comment by CorWatts** [comment]
Hey @brandogamus I wanted to let you know I've finally fixed this issue. Past check-ins won't be affected (and will still have an incorrect question answer <-> behavior association) but new check-ins will be correct now.

**Comment by brandogamus** [comment]
Thanks Corey! Keep up the great work. 

Brandon
