### ISSUE TITLE
Let's Encrypt Certificate Expired

### ISSUE THREAD

**Issue by rolemartyr-x** [CorWatts/fasterscale#197]
### How do we reproduce the problem?
Navigate to the website - get a security/expired certificate error

### What's expected?
Navigate securely to page without security errors

### What do you get instead?
certificate error

### Additional info
| Q                            | A
| ---------------------------- | ---
| PHP version                  |
| Operating System and Browser |

**Comment by CorWatts** [comment]
Thanks @rolemartyr-x , I recently migrated the site to a new server and forgot to set up a cronjob for the certificate renewal. Should be all good now though.

Please let me know if you notice any more issues.
