### ISSUE TITLE
Mobile app and Api

### ISSUE THREAD

**Issue by mattJurz** [CorWatts/fasterscale#199]
Hi there, thank you for a fantastic piece of work. I will be using your app every day for some time.

It happens that I am a front-end / UI developer. I think it would be amazing to make a mobile app out of this project. How difficult would it be to enable REST API? I am a React developer, but I could contribute to making a React Native app. 

Best regards.
--
Mateusz

**Comment by CorWatts** [comment]
Hey Mateusz, thank you I'm happy you enjoy this application.

I really appreciate your offer to help create a mobile app. Unfortunately I have very little time and energy to work on this project. I used to have much more time to devote to it but I now have other priorities. I'm sorry but I'm not able to commit to developing a REST api for this application.
